name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          cache: "npm"
      - run: npm ci
      - run: npm run test
      - uses: codecov/codecov-action@v2

  # release:
  #   name: Release library if necessary
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next')

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: lts
  #     - uses: bahmutov/npm-install@v1
  #     - run: npx semantic-release
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
